"""create calculations table

Revision ID: ba9cc8f1838f
Revises: 7c28afc9c683
Create Date: 2026-02-25 02:30:52.405580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ba9cc8f1838f"
down_revision: Union[str, Sequence[str], None] = "7c28afc9c683"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("expression", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calculations_id"), "calculations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calculations_id"), table_name="calculations")
    op.drop_table("calculations")
    # ### end Alembic commands ###
